[build]
  publish = "src"
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[dev]
  publish = "src"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
