[build]
  publish = "src"
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[dev]
  publish = "src"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"
